//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class App
    {
        public int id { get; set; }
        public Nullable<int> client { get; set; }
        public Nullable<int> courses { get; set; }
        public Nullable<int> program { get; set; }
    
        public virtual Client Client1 { get; set; }
        public virtual Courses Courses1 { get; set; }
    }
}
