//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Themes
    {
        public int id { get; set; }
        public Nullable<int> topics { get; set; }
        public string name { get; set; }
    
        public virtual Topics Topics1 { get; set; }
    }
}
